import dayjs, { type Dayjs } from 'dayjs'

export type ScheduleRecurrenceType = 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'CUSTOM'

export interface ScheduleMarkers {
  /** Every visible date on which this task is scheduled. */
  scheduled: Set<string>
  /** Dates belonging to a multi-day occurrence. */
  range: Set<string>
  /** Dates generated by a recurrence rule rather than a single date/range. */
  recurring: Set<string>
}

interface RecurrenceRule {
  frequency: 'DAILY' | 'WEEKLY' | 'MONTHLY'
  interval: number
  /** Fixed for normal MONTHLY; null means CUSTOM follows the previous due day. */
  preferredDay: number | null
}

function dateKey(value: Dayjs): string {
  return value.format('YYYY-MM-DD')
}

function parseDate(value: string | null | undefined): Dayjs | null {
  if (!value) return null
  const parsed = dayjs(value).startOf('day')
  return parsed.isValid() ? parsed : null
}

function recurrenceRule(
  type: ScheduleRecurrenceType | string | null | undefined,
  config: Record<string, number | string> | null | undefined,
  start: Dayjs,
): RecurrenceRule | null {
  const normalizedType = String(type ?? 'NONE').toUpperCase()
  if (normalizedType === 'NONE') return null

  const frequency = normalizedType === 'CUSTOM'
    ? String(config?.frequency ?? '').toUpperCase()
    : normalizedType
  if (frequency !== 'DAILY' && frequency !== 'WEEKLY' && frequency !== 'MONTHLY') return null

  const parsedInterval = Number(config?.interval ?? 1)
  const configuredDay = config?.day
  return {
    frequency,
    interval: Number.isFinite(parsedInterval) ? Math.max(1, Math.floor(parsedInterval)) : 1,
    preferredDay: configuredDay !== undefined && configuredDay !== null
      ? Number(configuredDay)
      : normalizedType === 'CUSTOM' && frequency === 'MONTHLY' ? null : start.date(),
  }
}

function addMonths(value: Dayjs, months: number, preferredDay: number | null): Dayjs {
  const month = value.startOf('month').add(months, 'month')
  const day = preferredDay ?? value.date()
  return month.date(Math.min(Math.max(1, day), month.daysInMonth())).startOf('day')
}

function advance(value: Dayjs, rule: RecurrenceRule, steps = 1): Dayjs {
  if (rule.frequency === 'DAILY') return value.add(rule.interval * steps, 'day')
  if (rule.frequency === 'WEEKLY') return value.add(rule.interval * steps, 'week')
  return addMonths(value, rule.interval * steps, rule.preferredDay)
}

function firstOccurrenceAtOrBefore(
  start: Dayjs,
  visibleStart: Dayjs,
  rule: RecurrenceRule,
): Dayjs {
  if (visibleStart.isBefore(start, 'day')) return start

  if (rule.frequency === 'MONTHLY') {
    const monthDistance = (visibleStart.year() - start.year()) * 12 + visibleStart.month() - start.month()
    const steps = Math.max(0, Math.floor(monthDistance / rule.interval) - 1)
    return advance(start, rule, steps)
  }

  const unitDays = rule.frequency === 'WEEKLY' ? 7 : 1
  const dayDistance = visibleStart.diff(start, 'day')
  const steps = Math.max(0, Math.floor(dayDistance / (unitDays * rule.interval)) - 1)
  return advance(start, rule, steps)
}

function markSpan(
  markers: ScheduleMarkers,
  visibleDays: Dayjs[],
  start: Dayjs,
  end: Dayjs,
  recurring: boolean,
) {
  for (const day of visibleDays) {
    if (day.isBefore(start, 'day') || day.isAfter(end, 'day')) continue
    const key = dateKey(day)
    markers.scheduled.add(key)
    if (!start.isSame(end, 'day')) markers.range.add(key)
    if (recurring) markers.recurring.add(key)
  }
}

/**
 * Expand the current task schedule only across the dates rendered by a
 * calendar. This keeps the UI clear without creating future database rows.
 */
export function getScheduleMarkers(options: {
  startDate: string | null | undefined
  endDate?: string | null
  recurrenceType?: ScheduleRecurrenceType | string | null
  recurrenceConfig?: Record<string, number | string> | null
  visibleDays: Dayjs[]
}): ScheduleMarkers {
  const markers: ScheduleMarkers = {
    scheduled: new Set(),
    range: new Set(),
    recurring: new Set(),
  }
  if (!options.visibleDays.length) return markers

  const start = parseDate(options.startDate)
  if (!start) return markers
  const end = parseDate(options.endDate) ?? start
  const durationDays = Math.max(0, end.diff(start, 'day'))
  const rule = recurrenceRule(options.recurrenceType, options.recurrenceConfig, start)

  if (!rule) {
    markSpan(markers, options.visibleDays, start, start.add(durationDays, 'day'), false)
    return markers
  }

  const visibleStart = options.visibleDays[0].startOf('day')
  const visibleEnd = options.visibleDays[options.visibleDays.length - 1].startOf('day')
  let occurrence = firstOccurrenceAtOrBefore(start, visibleStart, rule)
  let count = 0
  while (!occurrence.isAfter(visibleEnd, 'day') && count < 1000) {
    markSpan(markers, options.visibleDays, occurrence, occurrence.add(durationDays, 'day'), true)
    occurrence = advance(occurrence, rule)
    count += 1
  }
  return markers
}
