name: workfollow_personal
description: 打勾 · 个人任务与笔记
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
